package= { name= 'laser', version= '0.0.0', edition= '2021' }

[dependencies]
fehler = '*'
rand_xoshiro = '*'
rand = '*'
atomic_float = '*'
num = { git= 'https://github.com/Matthias-Fauconneau/num' }
vector = { git= 'https://github.com/Matthias-Fauconneau/vector' }
image = { git= 'https://github.com/Matthias-Fauconneau/image' }
ui = { git= 'https://github.com/Matthias-Fauconneau/ui' }

#[patch.'https://github.com/Matthias-Fauconneau/ui']
#ui = {path='../ui'}
#[patch.'https://github.com/Matthias-Fauconneau/image']
#image = {path='../image'}
#[patch.'https://github.com/Matthias-Fauconneau/num']
#num = {path='../num'}
